version: '3.8'

services:
  react-site:
    build: .
    container_name: react-site
    ports:
      - "8080:80"
    restart: always
    volumes:
      - .:/app
    command: sh -c "cd /app && git pull && npm install && npm run build && nginx -g 'daemon off;'"